FREAKUSB  = freakusb_main.c cdc.c desc.c ep.c hw.c isr.c usb_buf.c usb.c ctrl.c \

FREAKUSBDIRS += $(FREAKUSB_PATH) ${addprefix $(FREAKUSB_PATH)/, demo/contiki_usb class/CDC hw/at90usb usb }
FREAKUSB_OBJFILES = ${addprefix $(OBJECTDIR)/,${call oname, $(FREAKUSB)}}

SOURCEDIRS += $(FREAKUSB)
CONTIKI_SOURCEFILES += $(FREAKUSB)
PROJECT_OBJECTFILES += $(FREAKUSB_OBJFILES)
CONTIKIDIRS += $(FREAKUSBDIRS)
